theme: jekyll-theme-chirpy
sass:
  style: compressed

# Add your custom CSS
assets:
  custom_css: /assets/css/custom.scss

lang: en
timezone: Asia/Kolkata

title: "PURVI JAIN"
tagline: "Exploring the ethics of AI, one mini-project at a time."
description: >-
  A blog and portfolio by Purvi Jain, exploring the intersection of AI, ethics, and digital governance.

url: "https://purvi9399.github.io"
baseurl: ""
avatar: /assets/img/avatar.jpg

author:
  name: "Purvi Jain"
  email: "ipurvijain@gmail.com"

github:
  username: purvi9399

linkedin: 
  username: purvi-jain7

email: ipurvijjain@gmail.com

youtube: 
   username: @unitedbyfascinationforlearning

medium: 
 username: @passionatepurvi07

theme_mode: dark

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title


