theme: jekyll-theme-chirpy

lang: en
timezone: Asia/Kolkata

title: "AI Ethics Explorer"
tagline: "Exploring the ethics of AI, one mini-project at a time."
description: >-
  A blog and portfolio by Purvi Jain — exploring the intersection of AI, ethics, and digital governance.

url: "https://purvi9399.github.io"
baseurl: ""

author:
  name: "Purvi Jain"
  email: "your@email.com"

github:
  username: purvi9399

theme_mode: light

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:t

